stages:
  prepare_data:
    cmd: python prepare_data.py
    deps:
    - prepare_data.py
    outs:
    - combined_data.csv
  train:
    cmd: python train.py
    deps:
    - train.py
    - combined_data.csv
    outs:
    - shap_waterfall_plot.png
    metrics:
    - metrics.json:
        cache: false
