name: m5
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          pip install -r dvc_hw/requirements.txt
          dvc repro

          git fetch --prune
          dvc metrics diff --show-md main > report.md

          # Add figure to the report
          echo "## Feature importance"
          cml-publish shap_waterfall_plot.png --md >> report.md
          cml-send-comment report.md